---
title: CollectionBuilder-GH
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh
tagline: a siteleaf experiment
description: Generally a cool thing this site
author: dcn
metadata: demo-metadata
exclude:
- docs/
- Rakefile
- README.md
- LICENSE
- CITATION.cff
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
sass:
  style: compressed
